spring:
  application:
    name: upAndDownload

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Eddy2357

  jpa:
    hibernate:
      ddl-auto: update


server:
  servlet:
    context-path: /api/v1
  port: 8083